### ISSUE TITLE
Can't Build Project on Windows

### ISSUE THREAD

**Issue by esayitch** [KevinMFinch/UnityDrivingSim#1]
Hey!

Downloaded the project and purchased both Gaia and EasyRoads3D pro. Opened project in Unity 2017.1, imported packages, but I get several compilation errors similar to this:

Assets/Scripts/Simulation/CreateRoads.cs(16,9): error CS0246: The type or namespace name `ERRoadNetwork' could not be found. Are you missing an assembly reference?

It made me wonder... was this originally created on a linux device? Would make sense with the machine learning needs, but I wanted to make sure.

If this indeed has been developed on linux (Ubuntu?), how recommended is the linux unity editor version? Is it far behind the current windows release?

Thanks.

**Comment by KevinMFinch** [comment]
Ah, okay. Make sure you are using the EasyRoads3D version 3 beta. If you import EasyRoads3D in the Unity project, there is a Unity asset that imports the version 3 beta. Version 3 is the version that allows scripting.

**Comment by KevinMFinch** [comment]
As for machine learning needs, that has not yet been implemented as this is just a work in progress prototype.

**Comment by esayitch** [comment]
Hey, turns out it was indeed the EasyRoads3D asset that should import all of the v3 things... I hadn't run it before.
Thanks!
